// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aooxosvswlcivjawilqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvb3hvc3Zzd2xjaXZqYXdpbHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MTYxNjAsImV4cCI6MjA1MjE5MjE2MH0.MwaBh7pLDzjOrKgoQMIBBthh6cpXN1wELH55pYbsBFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);